### ISSUE TITLE
Then how does `Bitdell` creates a PR?

### ISSUE THREAD

**Issue by yask123** [hemanth/npm-janitor#1]
```
We don't currently allow bots to create issues, comments, and PRs. This usually ends up in repo owners reporting these things as spam.
```

If you activate bitdell for your repository, it automatically sends a PR with `badge` commit in readme file. 
https://bitdeli.com/

**Comment by yask123** [comment]
Err, just realised they ask for user authorisation. oops!.

**Comment by hemanth** [comment]
:cactus:
